apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: "bluecompute"
    env: dev
  name: demo-bluecompute-dev
  namespace: dev
spec:
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
  selector:
    matchLabels:
      app: "bluecompute-app"
status: {}
