apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bluecompute-web-dev
  namespace: dev
  labels:
    app: "bluecompute-app"
spec:
    type: GitHub
    pathname: https://github.com/rampadc/devops-demo-dev-env.git
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bluecompute-catalog
  namespace: dev
  labels:
    app: "bluecompute-app"
spec:
    type: GitHub
    pathname: https://github.com/hollisc/bluecompute-catalog-ops.git
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bluecompute-customer
  namespace: dev
  labels:
    app: "bluecompute-app"
spec:
    type: GitHub
    pathname: https://github.com/hollisc/bluecompute-customer-ops.git
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bluecompute-inventory
  namespace: dev
  labels:
    app: "bluecompute-app"
spec:
    type: GitHub
    pathname: https://github.com/hollisc/bluecompute-inventory-ops.git
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bluecompute-orders
  namespace: dev
  labels:
    app: "bluecompute-app"
spec:
    type: GitHub
    pathname: https://github.com/hollisc/bluecompute-orders-ops.git
